version: '2'
services:
  web:
    build: .
    ports:
     - "5000:5000"
    volumes:
     - .:/usr/src/app
    depends_on:
     - mongo
    environment:
     - DISPATCHER_PORT=5017
     - SINK_PORT=5016

  mongo:
    image: mongo
    volumes:
     - /usr/local/share/data:/data/db